name: io-webapp
version: '1.0'
summary: IO.st WebAPP
description: |
  WebAPP version of the IO.st web application.

grade: stable
confinement: strict

apps:
  ubuntu-webapp:
    command: webapp-launcher --enable-back-forward --webappUrlPatterns=https?://cashBOX.plus/* https://cashBOX.plus/
    plugs:
      - browser-sandbox
      - network
      - opengl
      - unity7

plugs:
  browser-sandbox:
    interface: browser-support
    allow-sandbox: false
  platform:
    interface: content
    content: ubuntu-app-platform1
    target: ubuntu-app-platform
    default-provider: ubuntu-app-platform

parts:
  webapp-container:
    plugin: nil
    after: [desktop-ubuntu-app-platform, webapp-helper]

